version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/node.conf:/etc/nginx/conf.d/node.template
      - ./ssl/coolhahow.xyz.crt:/etc/nginx/ssl/ssl.csr # if run docker on local, comment 
      - ./ssl/coolhahow.xyz.key:/etc/nginx/ssl/ssl.key # if run docker on local, comment 

    ports:
      - 80:80
      - 443:443 # if run docker on local, comment 
    command: 'bash -c "cat /etc/nginx/conf.d/node.template > /etc/nginx/conf.d/default.conf && nginx -g ''daemon off;''"'
  node:
    ports:
      - 3000:3000
    build: .
  redis:
    image: redis:alpine
    ports:
      - 6379:6379